---
title: "PW_Communications"
output: html_document
---

```{r}
library(tidyverse)
library(trelliscopejs)
library(plotly)
library(ggplot2)
library(purrr)
library(tidyr)
library(tidyselect)
library(plotly)
library(tidycensus)
library(stringr)
```


```{r}
census_api_key("b5f34962b7764c50ed301496b757b7c802d2e876", install = TRUE, overwrite = TRUE)

readRenviron("~/.Renviron")
```

```{r}
data <- get_decennial(
  geography="state", 
  variables="P1_001N",
  year=2020,
  output="wide")
```

```{r}
variable_names = c("B01003_001E", "B01001_001E", "B01001_002E", "B01001_003E", "B01001_004E", "B01001_005E", "B01001_006E", "B01001_007E", "B01001_008E", "B01001_009E", "B01001_010E", "B01001_011E", "B01001_012E", "B01001_013E", "B01001_014E", "B01001_015E", "B01001_016E", "B01001_017E", "B01001_018E", "B01001_019E", "B01001_020E", "B01001_021E", "B01001_022E", "B01001_023E", "B01001_024E", "B01001_025E", "B01001_026E", "B01001_027E", "B01001_028E", "B01001_029E", "B01001_030E", "B01001_031E", "B01001_032E", "B01001_033E", "B01001_034E", "B01001_035E", "B01001_036E", "B01001_037E", "B01001_038E", "B01001_039E", "B01001_040E", "B01001_041E", "B01001_042E", "B01001_042E", "B01001_042E", "B01001_042E", "B01001_042E", "B01001_042E")
```

```{r}
data2 <- get_acs(
  geography = "state",
  variables = c("B01003_001E", "B01001_001E"),
  year = 2017,
  endyear = NULL,
  output = "wide",
  state = NULL,
  county = NULL,
  zcta = NULL,
  geometry = FALSE,
  keep_geo_vars = FALSE,
  shift_geo = FALSE,
  summary_var = NULL,
  key = NULL,
  moe_level = 90,
  survey = "acs5",
  show_call = FALSE
)
```


```{r}
#view(data4)

years <- list(2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019)

#years <- list(2010, 2011)
```

```{r}
#create data frame with 0 rows and 3 columns
temp <- data.frame(matrix(ncol = 0, nrow = 0))

nrow(temp)

for (year in years) {

#send request for data from a specific year
data3 <- get_acs(
  geography = "state",
  table = "B01001",
  year = year,
  endyear = NULL,
  output = "wide",
  state = NULL,
  county = NULL,
  zcta = NULL,
  geometry = FALSE,
  keep_geo_vars = FALSE,
  shift_geo = FALSE,
  summary_var = NULL,
  key = NULL,
  moe_level = 90,
  survey = "acs1",
  show_call = FALSE
)

data4 <- data3 %>% pivot_longer(starts_with("B0"), names_to = "name")

var <- load_variables(year, "acs1")

new_var <- subset(var, select = -c(concept))


new_names <- left_join(data4, new_var, by = "name")

data5 <- data4 %>% 
  filter(str_sub(name, -1, -1) == "E") %>% 
  mutate(name = substr(name,1,nchar(name)-1) 
)
#I am a resting hippo
data6 <- left_join(data5, new_var, by="name") %>%
  mutate(year = year) %>%
  mutate(name = label) %>%
  select(-c(label))

data7 <- data6 %>% rename(Category = name) %>% select(-value, value)




if (nrow(temp) == 0) {
  temp <- data7
} else {
    temp <- rbind(temp, data7)
 }
}

```

```{r}
view(temp)

temp2 <- temp %>% pivot_wider(names_from = Category, values_from = value)

view(temp2)

temp3 <- write.csv(temp2)

write.csv(temp2, "homeless.csv", row.names = FALSE)
```








